### PR TITLE
fix: fixed reduce_order function to correctly handle requests that reduce an order's size to zero

### LINKED ISSUE #3: fix: Correct reduce logic in naive and direct implementations in the Orderbook
### Problem: 
`reduce_order` Incorrectly Rejects Full Reductions
In both naive_impl.rs and direct_impl.rs, the reduce_order function treats a request to reduce an order by its full remaining size as an error and rejects the command.

### Correct Behavior: 
As per reference logic, reducing an order by its full size is a valid operation equivalent to a cancellation. The function should detect this case and perform a full removal of the order from all data structures.

### Impact: 
This bug prevents users from cancelling orders via the reduce_order command, forcing them to use the cancel_order command instead.

### Affected Files:
orderbook/src/naive_impl.rs
orderbook/src/direct_impl.rs

### PR DESCRIPTION
**Pull request by RajasreePonnada**
- The function no longer incorrectly rejects a request to `reduce_order` by its full remaining size.
- It now correctly identifies this scenario as a call to `remove_order` and proceeds to completely remove the order from all associated data structures.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved order reduction logic with explicit size checks and consistent updates to order volumes and states.
  * Orders moved to a new price are now matched immediately, ensuring accurate filled amounts.

* **Tests**
  * Added tests verifying behavior when reducing an order to zero and for partial reductions, ensuring internal state consistency.

### CODE REVIEW

File: orderbook/tests/orderbook.rs [hunk 1]
```diff
@@ -62,4 +76,9 @@ fn test_simple_matching() {
     assert_eq!(order_book.get_order_by_id(1).unwrap().filled(), 5);
 }
 
-// TODO: translate all other tests from OrderBookBaseTest.java
+
+
+
+
+
+// TODO: translate all other tests from OrderBookBaseTest.java
```
Comment (rahulghangas) [inline orderbook/tests/orderbook.rs]: Remove this line completely

File: orderbook/src/naive_impl.rs [hunk 2]
```diff
@@ -339,36 +339,55 @@ impl<'a> OrderBook<'a> for OrderBookNaiveImpl {
...
+            return self.cancel_order(cmd);
+        }
+        cmd.matcher_event = Some(EventHelper::send_reduce_event(order, reduce_by, can_remove));
 
-            cmd.attach_matcher_event(EventHelper::send_reduce_event(order, reduced_by, false));
+        let buckets = if action == OrderAction::Ask {
+            &mut self.ask_buckets
+        } else {
+            &mut self.bid_buckets
+        };
```
Comment (rahulghangas) [inline orderbook/src/naive_impl.rs]: This logic, when reused multiple times, can lead to bugs. Extract this to a helper function

File: orderbook/src/naive_impl.rs [hunk 3]
```diff
@@ -339,36 +339,55 @@ impl<'a> OrderBook<'a> for OrderBookNaiveImpl {
...
+            (reduce_by, can_remove, order.price, order.action)
+        };
 
-            if let Some(bucket) = buckets.get_mut(&order.price) {
-                if let Some(o) = bucket.entries.get_mut(&order.order_id) {
-                    o.size = cmd.size;
-                }
-                bucket.reduce_size(reduced_by);
-            }
+        let order = self.order_id_map.get_mut(&order_id).unwrap();
```
Comment (rahulghangas) [inline orderbook/src/naive_impl.rs]: why do we get a reference (first immutable, then mutable) to the order twice? Refactor this to just do it once

File: orderbook/src/naive_impl.rs [hunk 4]
```diff
@@ -339,36 +339,55 @@ impl<'a> OrderBook<'a> for OrderBookNaiveImpl {
...
+        order.size -= reduce_by;
+        cmd.action = action;
```
Comment (rahulghangas) [inline orderbook/src/naive_impl.rs]: these don't need to be done if order can be removed

File: orderbook/src/naive_impl.rs [hunk 5]
```diff
@@ -339,36 +339,55 @@ impl<'a> OrderBook<'a> for OrderBookNaiveImpl {
...
+        if can_remove {
+            return self.cancel_order(cmd);
```
Comment (rahulghangas) [inline orderbook/src/naive_impl.rs]: this logic is also wrong. Order should't actually get cancelled here

File: orderbook/src/naive_impl.rs [hunk 6]
```diff
@@ -339,36 +339,55 @@ impl<'a> OrderBook<'a> for OrderBookNaiveImpl {
...
+        }
+        cmd.matcher_event = Some(EventHelper::send_reduce_event(order, reduce_by, can_remove));
 
-            cmd.attach_matcher_event(EventHelper::send_reduce_event(order, reduced_by, false));
```
Comment (rahulghangas) [inline orderbook/src/naive_impl.rs:366]: why remove the helper?

File: orderbook/src/naive_impl.rs [hunk 7]
```diff
@@ -406,18 +425,28 @@ impl<'a> OrderBook<'a> for OrderBookNaiveImpl {
...
-            };
-            let bucket = new_buckets
-                .entry(order.price)
-                .or_insert_with(|| OrdersBucketNaive::new(order.price));
-            bucket.put(&order);
-            self.order_id_map.insert(order.order_id, order);
+            cmd.action = order.action;
+            cmd.uid = order.uid;
+            cmd.order_id = order.order_id;
+            cmd.size = order.size;
```
Comment (rahulghangas) [inline orderbook/src/naive_impl.rs]: why is this being done?

**Review by rahulghangas — CHANGES_REQUESTED** [review]

File: orderbook/tests/orderbook.rs (hunk 1 above)
Comment (RajasreePonnada) [reply orderbook/tests/orderbook.rs]: done, removed in #[93f19d3](https://github.com/trade-vex/vex-core/pull/4/commits/93f19d304417bcc6d5ef652deb56ae5108b85bec)

File: orderbook/src/naive_impl.rs (hunk 2 above)
Comment (RajasreePonnada) [reply orderbook/src/naive_impl.rs]: added helper function in #[93f19d3](https://github.com/trade-vex/vex-core/pull/4/commits/93f19d304417bcc6d5ef652deb56ae5108b85bec)

File: orderbook/src/naive_impl.rs (hunk 3 above)
Comment (RajasreePonnada) [reply orderbook/src/naive_impl.rs]: refactored in [93f19d3](https://github.com/trade-vex/vex-core/pull/4/commits/93f19d304417bcc6d5ef652deb56ae5108b85bec)

File: orderbook/src/naive_impl.rs (hunk 4 above)
Comment (RajasreePonnada) [reply orderbook/src/naive_impl.rs]: resolved in [93f19d3](https://github.com/trade-vex/vex-core/pull/4/commits/93f19d304417bcc6d5ef652deb56ae5108b85bec)

File: orderbook/src/naive_impl.rs (hunk 5 above)
Comment (RajasreePonnada) [reply orderbook/src/naive_impl.rs]: the order is just removed now in [93f19d3](https://github.com/trade-vex/vex-core/pull/4/commits/93f19d304417bcc6d5ef652deb56ae5108b85bec)

File: orderbook/src/naive_impl.rs (hunk 6 above)
Comment (RajasreePonnada) [reply orderbook/src/naive_impl.rs:366]: added in [93f19d3](https://github.com/trade-vex/vex-core/pull/4/commits/93f19d304417bcc6d5ef652deb56ae5108b85bec)

File: orderbook/src/naive_impl.rs (hunk 7 above)
Comment (RajasreePonnada) [reply orderbook/src/naive_impl.rs]: it is redundant [93f19d3](https://github.com/trade-vex/vex-core/pull/4/commits/93f19d304417bcc6d5ef652deb56ae5108b85bec)

File: orderbook/src/naive_impl.rs (hunk 3 above)
Comment (rahulghangas) [reply orderbook/src/naive_impl.rs]: No this hasn't been resolved

Comment (rahulghangas) [reply orderbook/src/naive_impl.rs]: I can still see 2 references being taken. Code rabbit also picked i t up in its review below

File: orderbook/src/naive_impl.rs (hunk 5 above)
Comment (rahulghangas) [reply orderbook/src/naive_impl.rs]: it's not being removed from the map

File: orderbook/src/naive_impl.rs [hunk 8]
```diff
@@ -406,18 +452,21 @@ impl<'a> OrderBook<'a> for OrderBookNaiveImpl {
...
+
+            // Insert into new bucket only if partially filled or not filled at all
+            if order.size > order.filled {
+                let new_buckets = self.get_buckets_mut(order.action);
+                let bucket = new_buckets
+                    .entry(order.price)
+                    .or_insert_with(|| OrdersBucketNaive::new(order.price));
+                bucket.put(&order);
+                self.order_id_map.insert(order.order_id, order);
+            }
```
[the remark this answers is not in the document]
Comment (rahulghangas) [reply orderbook/src/naive_impl.rs:470]: @coderabbitai create tracking issue for this (referencing this PR)

**Review by rahulghangas — APPROVED** [review]
